# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./travis-tool.sh install_r RJSONIO
  - ./run.sh install_aptget r-cran-curl

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

# tests require tokens so ...  
#after_success:
#  - ./run.sh coverage
   
notifications:
  email:
    on_success: change
    on_failure: change

